export default [
  'valentina',
  'pirje',
  'triin',
  'ants',
  'lisa',
  'mervi',
  'martin',
  'kadri',
  'kristel',
  'kertu',
  'erik',
  'chris',
  'madis',
  'talvar',
  'medea',
  'marco',
  'dajana',
  'hendrik',
  '', // TODO: Who dis? bicycle + spaghetti 🤔
  'markko',
  'diogo',
  'ann',
  'annika',
  'reigo',
  'pēteris',
  'mihkel',
  'niclas',
  'merit',
  'lilian',
  'daniel',
  'fredi',
  'merily',
  // TODO: pics too low-res
  // 'valentina', 'lisa', 'merit', 'martin',
  // TODO: missing
  // 'kaire', 'kamil', 'kair', 'joonathan', 'egon',
]